# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- features/3.3.5-mac-build

pool:
  vmImage: macOS-latest

steps:
- script: |
    brew update
    brew install mysql readline boost
    export CC=gcc-11
    export CXX=g++-11
  displayName: 'Dependencies'
- script: |
    mkdir bin
    cd bin
    cmake ../ -G "Xcode" -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DBUILD_TESTING=1
    cd ..
  displayName: 'Setup'
- script: |
    cd bin
    make -j 4 -k && make install
  displayName: 'Build'
- script: |
    cd bin
    make test
  displayName: 'Unit tests'
- script: |
    cd bin/check_install/bin
    ./authserver --version
    ./worldserver --version
  displayName: 'Check executables'
